<?
$lang = array (
	'Created by:' => '',
	'Licence:' => '',
	'File name:' => '',
	'File size:' => '',
	'Creation date:' => '',
	'Camera maker:' => '',
	'Camera model:' => '',
	'Size:' => '',
	'seconds' => '',
	'F number:' => '',
	'Size:' => '',
	'Settings' => '',
	'No' => '',
	'High quality preview' => '',
	'Default: disabled' => '',
	'low performance' => '',
	'High quality preview improves the preview quality in the info window, by downloading a full version of the image from the server (instead of a scaled-down version)and scaling it down in-browser. Using this feature will allow to zoom in and out. This is not recommended for slow connections. High quality preview is always enabled for files smaller than 1 MiB.' => '',
	'Hash link to the info window' => '',
	'Default: enabled' => '',
	'comfortable' => '',
	'Hash link to the info window changes the address add add a picture ID to it when opening the info window. Using this feature will allow copying a link to open the page and the info window and sending it to friends to point them to a specific picture, but might flood the browser history with entry for every picture viewed.' => '',
	'Zoom in' => '',
	'Zoom out' => '',
	'Next picture' => '',
	'Previous picture' => '',
	'Hide metadata' => '',
	'*Available in high quality preview only' => '',
	'Keyboard shortcuts' => ''
);
?>
